### ISSUE TITLE
adding new nodes. User node not copied to nodered user config folder?

### ISSUE THREAD

**Issue by dpap** [Agile-IoT/secure-nodered#1]
How do you add new nodes to secure-nodered?

On the console it seems to be reading from "User directory : ./.nodered/" which is located in /opt/secure-nodered

but from docker-compose I see   
volumes:
      - $DATA/nodered:/root/.node-red

I do find that if I make a folder there this will be visible inside the container. But it doesn't seem to be copied to the local folder

**Comment by cskiraly** [comment]
Was fixed some days ago here: https://github.com/Agile-IoT/agile-stack/commit/07dc33090773afd1d352778d4a94edb85a2c18ff
Is your stack on the master branch?

**Comment by dpap** [comment]
I'm using agile-scripts. agile-stack has not been updated there (HEAD detached at 7b3de1a). 
I pulled agile-stack:master inside scripts and it's ok.

**Comment by cskiraly** [comment]
agile-scripts' master is still on the latest stable release. Given its use, I think we will only update it once we have a new tested stable release.
